name: Haskell CI
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  haskell-ci:
    name: Haskell CI
    uses: bellroy/actions/.github/workflows/haskell-os-ci.yaml@haskell-ci
    with:
      cabal-file-relative-path: aws-arn
